### ISSUE TITLE
Gateway is running `AuthCookieFilter` for `/actuator/health` endpoint.

### ISSUE THREAD

**Issue by voidCounter** [Learnathon-By-Geeky-Solutions/byte-bandit#204]
### Steps to Reproduce

1. Go to `/byte-bandit`. 
2. Run `./run-services.sh start backend`
3. Running fails due to missing `auth_cookie` that's being checking in the `CookieUtil.java`. 

### Additional Information
This is happening because docker runs `actuator/health` to check health of starting services. 
Currently we're having 
```yaml
app:
  permitted:
    routes: /api/v1/auth/login,/api/v1/user/register,/api/v1/user/resend-verification,/api/v1/user/verify,/api/v1/auth/csrf,/api/v1/auth/test-csrf,/actuator/*
```
this permitted routes in the configuration of gateway. But we're not considering pattern matching in `AuthCookieFilter` to skip running for permitted routes. Having `/actuator/health` fixes the issue. But we should also support pattern matching in the `AuthCookieFilter` to support wild-card based paths.
